### ISSUE TITLE
Add cabal-fmt as alternative

### ISSUE THREAD

**Issue by hasufell** [kowainik/autopack#13]
https://oleg.fi/gists/posts/2019-08-11-cabal-fmt.html can expand directories:

```
-- cabal-fmt: expand src
exposed-modules:
  CabalFmt
  ...
```

Then running `cabal-fmt` will update exposed-modules.

---

On another note:

There was also a short discussion about autopack in `#haskell` recently and it seems it's a bit controversial. Some voices think it's an abuse of the custom Setup feature and breaks the .cabal file as source-of-truth-metadata.

What I think about this is: once cabal has hooks (e.g. run script XY prior to `build`/`install`), then this would be, in conjunction with cabal-fmt, a sufficient hpack replacement. I'm not sure of the state of hooks in cabal and whether it's still just an idea.

**Comment by vrom911** [comment]
I believe `autopack` never was stated as the replacement to hpack. It is just our experiment that we had all rights to do. And we are not forcing anyone to use it. 
If your statement is about removing/deprecating/whatever our package, then I refuse to do so, as this is just a hobby project that was created for the sake of curiosity primarily.

**Comment by hasufell** [comment]
> If your statement is about removing/deprecating/whatever our package, then I refuse to do so, as this is just a hobby project that was created for the sake of curiosity primarily.

Oh, absolutely not. I was just suggesting to add cabal-fmt as an alternative :)

And then I rembered the discussion around it. I am currently using autopack in local development mode.
